# Generated by Django 2.2.6 on 2019-11-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jname', models.CharField(max_length=128, unique=True)),
                ('jid', models.CharField(max_length=128, unique=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
