# Generated by Django 2.2.6 on 2019-11-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsl', '0002_job_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=128, unique=True)),
                ('IP', models.CharField(max_length=128, unique=True)),
                ('keyname', models.CharField(max_length=128, unique=True)),
                ('infro', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
