# Generated by Django 2.2.6 on 2019-11-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsl', '0004_auto_20191106_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_host',
            name='IP',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='add_host',
            name='infro',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='add_host',
            name='keyname',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='add_host',
            name='port',
            field=models.CharField(max_length=128),
        ),
    ]
