# Generated by Django 2.2.6 on 2019-11-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsl', '0005_auto_20191106_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_host',
            name='username',
            field=models.CharField(default='root', max_length=128),
        ),
    ]
