# Generated by Django 2.2.6 on 2019-11-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsl', '0006_add_host_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jname', models.CharField(max_length=128, unique=True)),
                ('jid', models.CharField(max_length=128, unique=True)),
                ('exec_host', models.CharField(max_length=128, unique=True)),
                ('exec_history', models.CharField(max_length=128, unique=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='add_host',
            name='username',
            field=models.CharField(max_length=128),
        ),
    ]
