# Generated by Django 2.2.6 on 2019-11-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsl', '0007_auto_20191119_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_history',
            name='jname',
            field=models.CharField(max_length=128),
        ),
    ]
