# Generated by Django 2.2.6 on 2020-05-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsl', '0008_auto_20191120_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='update_version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_name', models.CharField(default='upname', max_length=254)),
                ('ser_name', models.CharField(max_length=254, null=True)),
                ('ios_cname', models.CharField(max_length=254, null=True)),
                ('aos_cname', models.CharField(max_length=254, null=True)),
                ('env', models.CharField(max_length=254, null=True)),
                ('up_info', models.TextField(max_length=254, null=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='job_history',
            name='exec_host',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='job_history',
            name='jid',
            field=models.CharField(max_length=128),
        ),
    ]
