# Generated by Django 2.2.6 on 2020-05-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsl', '0009_auto_20200506_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update_version',
            name='up_name',
            field=models.CharField(max_length=254),
        ),
    ]
