# Generated by Django 2.2.6 on 2020-05-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsl', '0011_update_version_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='update_version',
            name='progress',
            field=models.CharField(default='进行中', max_length=128),
        ),
        migrations.AlterField(
            model_name='update_version',
            name='status',
            field=models.CharField(default='label-info', max_length=128),
        ),
    ]
